### ISSUE TITLE
Why californium  sending  65565 records only?

### ISSUE THREAD

**Issue by avishu2111** [mkovatsc/Californium#68]
Below is the snippet. I have 1000000 records but it sends only 65565 records.

	try {						
			long startTime = System.currentTimeMillis();
			for (int i = 0; i < 1000000; i++) {
				Request req = new Request(Code.POST);
				req.setURI(new URI("coap://192.168.15.170:5683/helloWorld"));
				req.setPayload("ok");
				req.setMID(i);
				req.send();
				Response response = req.waitForResponse();
				System.out.println( response.getPayloadString());	
			}		
			System.out.println("done");			
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}catch (Exception e) {
			e.printStackTrace();
		}

**Comment by Lanterm** [comment]
Notice that a CoAP message is identified my its endpoint and a 16-bit message ID (MID). This allows for about 250 messages per second (see https://tools.ietf.org/html/rfc7252#section-2.1). If your destination endpoint is a local instance, your throughput may be above this limit. However, I am going to look into it when I have time. Even if it the problem is massive throughput, Cf should give you proper information about what the problem is.

**Comment by avishu2111** [comment]
Thanks for immediate response. I have added some delay and it's working fine.
